class MenuLateral:
    btn_resend_receipt_menu = "btn_resend_receipt_menu"
    btn_refund_menu = "btn_refund_menu"
    btn_reports_menu = "btn_reports_menu"
    btn_manage_terminal_menu = "btn_manage_terminal_menu"
    btn_developer_options_menu = "btn_developer_options_menu"
    btn_merchant_info_menu = "btn_merchant_info_menu"
    btn_operators_menu = "btn_operators_menu"
    btn_initialization_menu = "btn_initialization_menu"
    btn_apps_menu = "btn_apps_menu"
    btn_test_menu = "btn_test_menu"
    btn_reset_data_menu = "btn_reset_data_menu"
    btn_export_data_menu = "btn_export_data_menu"
    btn_last_error_menu = "btn_last_error_menu"
    btn_settings_menu = "btn_settings_menu"
    btn_app_information_menu = "btn_app_information_menu"
    btn_device_menu = "btn_device_menu"
    btn_supervisor_options_menu = "btn_supervisor_options_menu"